FROM node:23.11.0-slim

RUN apt update
RUN apt upgrade -y
RUN apt install -y curl git build-essential
RUN npm install -g @nestjs/cli

COPY start.sh /
RUN chmod +x /start.sh
USER node
WORKDIR /home/node/app
EXPOSE 3000
EXPOSE 5672
EXPOSE 3306
CMD ["/start.sh"] 