services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/home/node/app
  database:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_USER: orders
      MYSQL_PASSWORD: orders
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - '15672:15672'
      - '5672:5672'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      RABBITMQ_DEFAULT_USER: orders
      RABBITMQ_DEFAULT_PASS: orders
    volumes:
      - ./docker/rabbitmq_data:/var/lib/rabbitmq
